require: rubocop-rspec

RSpec/NamedSubject:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 12

Style/Documentation:
  Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: False
