Metrics/AbcSize:
    Exclude:
          - 'application.rb'

Metrics/MethodLength:
    Exclude:
          - 'application.rb'
Style/Documentation:
    Enabled: false
Style/ClassVars:
    Enabled: false
